// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamemsg.proto

#include "gamemsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Game {
}  // namespace Game
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_gamemsg_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_gamemsg_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gamemsg_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gamemsg_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_gamemsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rgamemsg.proto\022\004Game*\251\001\n\007MsgType\022\016\n\nTYP"
  "E_BEGIN\020\000\022\026\n\022TYPE_LOGIN_ID_NAME\020\001\022\025\n\021TYP"
  "E_CHAT_CONTENT\020\002\022\025\n\021TYPE_NEW_POSITION\020\003\022"
  "\023\n\016TYPE_BROADCAST\020\310\001\022\030\n\023TYPE_LOGOUT_ID_N"
  "AME\020\311\001\022\031\n\024TYPE_AROUND_POSITION\020\312\001b\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_gamemsg_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_gamemsg_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gamemsg_2eproto_once;
static bool descriptor_table_gamemsg_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gamemsg_2eproto = {
  &descriptor_table_gamemsg_2eproto_initialized, descriptor_table_protodef_gamemsg_2eproto, "gamemsg.proto", 201,
  &descriptor_table_gamemsg_2eproto_once, descriptor_table_gamemsg_2eproto_sccs, descriptor_table_gamemsg_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_gamemsg_2eproto::offsets,
  file_level_metadata_gamemsg_2eproto, 0, file_level_enum_descriptors_gamemsg_2eproto, file_level_service_descriptors_gamemsg_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gamemsg_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_gamemsg_2eproto), true);
namespace Game {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gamemsg_2eproto);
  return file_level_enum_descriptors_gamemsg_2eproto[0];
}
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 200:
    case 201:
    case 202:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Game
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
